language: java
sudo: false

jdk:
- openjdk11

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.m2"

addons:
  chrome: stable

before_install:
- sudo service mysql stop

script:
- docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
- mvn clean package
- docker-compose up --build -d
- mvn integration-test -Dskip.functional.tests=false

after_success:
- docker tag jrc tpolishchuk/jrcatcher:${TRAVIS_BUILD_NUMBER}
- docker push tpolishchuk/jrcatcher:${TRAVIS_BUILD_NUMBER}
