FROM openjdk:12-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-Xdebug","-Xrunjdwp:server=y,transport=dt_socket,suspend=n", "-cp","app:app/lib/*","jrc.JRequestCatcherApplication"]
